<?php
/**
 * @file
 * load_documents.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function load_documents_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: navigation_add-file:file/add.
  $menu_links['navigation_add-file:file/add'] = array(
    'menu_name' => 'navigation',
    'link_path' => 'file/add',
    'router_path' => 'file/add',
    'link_title' => 'Add file',
    'options' => array(
      'alter' => TRUE,
      'identifier' => 'navigation_add-file:file/add',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Add file');

  return $menu_links;
}
