<?php
/**
 * @file
 * Code for the Demand create feature.
 */

include_once 'demand_create.features.inc';

function demand_create_form_profile2_form_alter(&$form, &$form_state) {

  unset($form['profile_demand_create']['field_paper_size']['und']['#options']['_none']);
  unset($form['profile_demand_create']['field_paper_orientation']['und']['#options']['_none']);
  unset($form['profile_demand_create']['field_header_setting_align']['und']['#options']['_none']);
  unset($form['profile_demand_create']['field_header_number_page']['und']['#options']['_none']);
  unset($form['profile_demand_create']['field_header_setting_font']['und']['#options']['_none']);
  unset($form['profile_demand_create']['field_header_setting_size']['und']['#options']['_none']);
  unset($form['profile_demand_create']['field_header_setting_color']['und']['#options']['_none']);
  unset($form['profile_demand_create']['field_header_setting_background']['und']['#options']['_none']);
  $form['profile_demand_create']['field_setting']['und']['#options']['_none'] = '';
  $form['profile_demand_create']['field_paper_size']['und']['#title'] = '';
  $form['profile_demand_create']['field_paper_orientation']['und']['#title'] = '';
  $form['profile_demand_create']['field_header_setting_font']['und']['#title'] = '';
  $form['profile_demand_create']['field_header_setting_size']['und']['#title'] = '';
  $form['profile_demand_create']['field_header_setting_typeface']['und']['#title'] = '';
  $form['profile_demand_create']['field_header_setting_color']['und']['#title'] = '';
  $form['profile_demand_create']['field_header_setting_background']['und']['#title'] = '';
  $form['profile_demand_create']['field_main_font_typeface']['und']['#title'] = '';
  $form['profile_demand_create']['field_main_interval_page2']['und'][0]['value']['#title'] = '';
  $form['profile_demand_create']['field_main_width_number2']['und'][0]['value']['#title'] = '';
  $form['profile_demand_create']['field_main_width_width2']['und'][0]['value']['#title'] = '';
  $form['profile_demand_create']['field_main_width_space2']['und'][0]['value']['#title'] = '';
  $form['profile_demand_create']['field_header_setting_align']['und']['#options'][1] = '<span></span>';
  $form['profile_demand_create']['field_header_setting_align']['und']['#options'][2] = '<span></span>';
  $form['profile_demand_create']['field_header_setting_align']['und']['#options'][3] = '<span></span>';
  $form['profile_demand_create']['field_header_setting_align']['und']['#title'] = '';
  $form['profile_demand_create']['field_header_setting_align']['#attributes']['class'][3] = 'n_visibl_r';
  $form['profile_demand_create']['field_header_setting_typeface']['und']['#options'][8] = '<span></span>';
  $form['profile_demand_create']['field_header_setting_typeface']['und']['#options'][9] = '<span></span>';
  $form['profile_demand_create']['field_header_setting_typeface']['und']['#options'][10] = '<span></span>';
  $form['profile_demand_create']['field_header_setting_typeface']['#attributes']['class'][3] = 'n_visibl';
  $form['profile_demand_create']['field_number_main_view']['#attributes']['class'][3] = 'n_visibl_n';
  $form['profile_demand_create']['field_pic_border_type']['und']['#options'][32] = '<span></span>';
  $form['profile_demand_create']['field_pic_border_type']['und']['#options'][33] = '<span></span>';
  $form['profile_demand_create']['field_pic_border_type']['und']['#options'][34] = '<span></span>';
  $form['profile_demand_create']['field_pic_border_type']['und']['#options'][35] = '<span></span>';
  $form['profile_demand_create']['field_pic_border_type']['und']['#options'][36] = '<span></span>';
  $form['profile_demand_create']['field_pic_border_type']['und']['#options'][37] = '<span></span>';
  $form['profile_demand_create']['field_pic_border_type']['und']['#options'][38] = '<span></span>';
  $form['profile_demand_create']['field_pic_border_type']['#attributes']['class'][3] = 'n_visibl_n';
  $form['profile_demand_create']['field_pic_align_pic']['und']['#options'][1] = '<span></span>';
  $form['profile_demand_create']['field_pic_align_pic']['und']['#options'][2] = '<span></span>';
  $form['profile_demand_create']['field_pic_align_pic']['und']['#options'][3] = '<span></span>';
  $form['profile_demand_create']['field_pic_align_pic']['#attributes']['class'][3] = 'n_visibl_r';
  $form['profile_demand_create']['field_pic_label_align']['und']['#options'][1] = '<span></span>';
  $form['profile_demand_create']['field_pic_label_align']['und']['#options'][2] = '<span></span>';
  $form['profile_demand_create']['field_pic_label_align']['und']['#options'][3] = '<span></span>';
  $form['profile_demand_create']['field_pic_label_align']['#attributes']['class'][3] = 'n_visibl_r';
  $form['profile_demand_create']['field_table_label_continue2']['und']['#options'][1] = '<span></span>';
  $form['profile_demand_create']['field_table_label_continue2']['und']['#options'][2] = '<span></span>';
  $form['profile_demand_create']['field_table_label_continue2']['und']['#options'][3] = '<span></span>';
  $form['profile_demand_create']['field_table_label_continue2']['#attributes']['class'][3] = 'n_visibl_r';
  $form['profile_demand_create']['field_title_number_view']['#attributes']['class'][3] = 'n_visibl_n';
  $form['profile_demand_create']['field_pic_number_view']['und']['#options'][12] = '<span></span>';
  $form['profile_demand_create']['field_pic_number_view']['#attributes']['class'][3] = 'n_visibl_n';
  $form['profile_demand_create']['field_table_number_view']['#attributes']['class'][3] = 'n_visibl_n';
  $form['profile_demand_create']['field_formula_number_view']['#attributes']['class'][3] = 'n_visibl_n';
  $form['profile_demand_create']['field_list_number_view']['#attributes']['class'][3] = 'n_visibl_n';
  $form['profile_demand_create']['field_main_font_font']['und']['#title'] = '';
  unset($form['profile_demand_create']['field_main_font_font']['und']['#options']['_none']);
  $form['profile_demand_create']['field_main_font_size']['und']['#title'] = '';
  unset($form['profile_demand_create']['field_main_font_size']['und']['#options']['_none']);
  unset($form['profile_demand_create']['field_main_font_align']['und']['#options']['_none']);
  $form['profile_demand_create']['field_main_font_align']['und']['#options'][28] = '<span></span>';
  $form['profile_demand_create']['field_main_font_align']['und']['#options'][29] = '<span></span>';
  $form['profile_demand_create']['field_main_font_align']['und']['#options'][30] = '<span></span>';
  $form['profile_demand_create']['field_main_font_align']['und']['#options'][31] = '<span></span>';
  $form['profile_demand_create']['field_main_font_align']['und']['#title'] = '';
  $form['profile_demand_create']['field_main_font_align']['#attributes']['class'][3] = 'n_visibl_r';
  $form['profile_demand_create']['field_main_font_typeface']['und']['#options'][8] = '<span></span>';
  $form['profile_demand_create']['field_main_font_typeface']['und']['#options'][9] = '<span></span>';
  $form['profile_demand_create']['field_main_font_typeface']['und']['#options'][10] = '<span></span>';
  $form['profile_demand_create']['field_main_font_typeface']['#attributes']['class'][3] = 'n_visibl';
  $form['profile_demand_create']['field_main_font_color']['und']['#title'] = '';
  unset($form['profile_demand_create']['field_main_font_color']['und']['#options']['_none']);
  $form['profile_demand_create']['field_main_font_background']['und']['#title'] = '';
  unset($form['profile_demand_create']['field_main_font_background']['und']['#options']['_none']);
  $form['profile_demand_create']['field_main_margins_str']['und']['#options']['_none'] = '(нет)';
  unset($form['profile_demand_create']['field_main_interval_str']['und']['#options']['_none']);
  unset($form['profile_demand_create']['field_main_columns_text']['und']['#options']['_none']);
  $form['profile_demand_create']['field_number_main_type']['und']['#options']['_none'] = '(нет)';
  unset($form['profile_demand_create']['field_number_main_view']['und']['#options']['_none']);
  $form['profile_demand_create']['field_number_main_division']['und']['#options']['_none'] = '(нет)';
  $form['profile_demand_create']['field_number_pattern_pic']['und']['#options']['_none'] = '(нет)';
  $form['profile_demand_create']['field_number_pattern_table']['und']['#options']['_none'] = '(нет)';
  $form['profile_demand_create']['field_title_main_level']['und']['#options']['_none'] = '(нет)';
  $form['profile_demand_create']['field_title_main_pattern']['und']['#options']['_none'] = '(нет)';
  $form['profile_demand_create']['field_title_number_type']['und']['#options']['_none'] = '(нет)';
  unset($form['profile_demand_create']['field_title_number_view']['und']['#options']['_none']);
  $form['profile_demand_create']['field_title_number_division']['und']['#options']['_none'] = '(нет)';
  $form['profile_demand_create']['field_pic_number_type']['und']['#options']['_none'] = '(нет)';
  unset($form['profile_demand_create']['field_pic_number_view']['und']['#options']['_none']);
  $form['profile_demand_create']['field_pic_number_division']['und']['#options']['_none'] = '(нет)';
  $form['profile_demand_create']['field_table_number_type']['und']['#options']['_none'] = '(нет)';
  unset($form['profile_demand_create']['field_table_number_view']['und']['#options']['_none']);
  $form['profile_demand_create']['field_table_number_division']['und']['#options']['_none'] = '(нет)';
  $form['profile_demand_create']['field_formula_number_type']['und']['#options']['_none'] = '(нет)';
  unset($form['profile_demand_create']['field_formula_number_view']['und']['#options']['_none']);
  $form['profile_demand_create']['field_formula_number_division']['und']['#options']['_none'] = '(нет)';
  unset($form['profile_demand_create']['field_list_formatting_level']['und']['#options']['_none']);
  $form['profile_demand_create']['field_list_number_type']['und']['#options']['_none'] = '(нет)';
  unset($form['profile_demand_create']['field_list_number_view']['und']['#options']['_none']);
  $form['profile_demand_create']['field_list_number_division']['und']['#options']['_none'] = '(нет)';
  unset($form['profile_demand_create']['field_quotes_main_symbol']['und']['#options']['_none']);
  unset($form['profile_demand_create']['field_pic_size_valid']['und']['#options']['_none']);
  $form['profile_demand_create']['field_pic_size_valid']['und']['#title'] = '';
  $form['profile_demand_create']['field_pic_size_1']['und'][0]['value']['#title'] = '';
  $form['profile_demand_create']['field_pic_size_2']['und'][0]['value']['#title'] = 'X   ';
  unset($form['profile_demand_create']['field_pic_indents_top2']['und']['#options']['_none']);
  $form['profile_demand_create']['field_pic_indents_top2']['und']['#title'] = '';
  unset($form['profile_demand_create']['field_pic_indents_text2']['und']['#options']['_none']);
  $form['profile_demand_create']['field_pic_indents_text2']['und']['#title'] = '';
  unset($form['profile_demand_create']['field_pic_indents_pic2']['und']['#options']['_none']);
  $form['profile_demand_create']['field_pic_indents_pic2']['und']['#title'] = '';
  $form['profile_demand_create']['field_main_columns_text']['und']['#title'] = '';
  unset($form['profile_demand_create']['field_formula_indents_formula2']['und']['#options']['_none']);
  $form['profile_demand_create']['field_formula_indents_formula2']['und']['#title'] = '';
  unset($form['profile_demand_create']['field_formula_indents_text2']['und']['#options']['_none']);
  $form['profile_demand_create']['field_formula_indents_text2']['und']['#title'] = '';
  unset($form['profile_demand_create']['field_table_label_continue2']['und']['#options']['_none']);
  $form['profile_demand_create']['field_table_label_continue2']['und']['#title'] = '';
  unset($form['profile_demand_create']['field_contents_main_position']['und']['#options']['_none']);
  $form['profile_demand_create']['field_contents_main_division']['und']['#options']['_none'] = '(нет)';
  unset($form['profile_demand_create']['field_pic_border_type']['und']['#options']['_none']);
  unset($form['profile_demand_create']['field_pic_align_pic']['und']['#options']['_none']);
  unset($form['profile_demand_create']['field_pic_label_align']['und']['#options']['_none']);
  $form['profile_demand_create']['field_pic_border_type']['und']['#title'] = '';
  $form['profile_demand_create']['field_pic_align_pic']['und']['#title'] = '';
  $form['profile_demand_create']['field_pic_label_align']['und']['#title'] = '';
  $form['profile_demand_create']['field_table_label_font']['und']['#title'] = '';
  unset($form['profile_demand_create']['field_table_label_font']['und']['#options']['_none']);
  $form['profile_demand_create']['field_table_label_size']['und']['#title'] = '';
  unset($form['profile_demand_create']['field_table_label_size']['und']['#options']['_none']);
  unset($form['profile_demand_create']['field_table_label_align']['und']['#options']['_none']);
  $form['profile_demand_create']['field_table_label_align']['und']['#options'][28] = '<span></span>';
  $form['profile_demand_create']['field_table_label_align']['und']['#options'][29] = '<span></span>';
  $form['profile_demand_create']['field_table_label_align']['und']['#options'][30] = '<span></span>';
  $form['profile_demand_create']['field_table_label_align']['und']['#options'][31] = '<span></span>';
  $form['profile_demand_create']['field_table_label_align']['und']['#title'] = '';
  $form['profile_demand_create']['field_table_label_align']['#attributes']['class'][3] = 'n_visibl_r';
  $form['profile_demand_create']['field_table_label_typeface']['und']['#options'][8] = '<span></span>';
  $form['profile_demand_create']['field_table_label_typeface']['und']['#options'][9] = '<span></span>';
  $form['profile_demand_create']['field_table_label_typeface']['und']['#options'][10] = '<span></span>';
  $form['profile_demand_create']['field_table_label_typeface']['und']['#title'] = '';
  $form['profile_demand_create']['field_table_label_typeface']['#attributes']['class'][3] = 'n_visibl';
  $form['profile_demand_create']['field_table_label_color']['und']['#title'] = '';
  unset($form['profile_demand_create']['field_table_label_color']['und']['#options']['_none']);
  $form['profile_demand_create']['field_table_label_background']['und']['#title'] = '';
  unset($form['profile_demand_create']['field_table_label_background']['und']['#options']['_none']);
  $form['profile_demand_create']['field_pic_size_1']['#attributes']['class'][] = 'width';
  $form['profile_demand_create']['field_pic_size_2']['#attributes']['class'][] = 'width';
  $form['profile_demand_create']['field_demand_name']['#attributes']['class'][] = 'width';
  $form['profile_demand_create']['field_demand_note']['#attributes']['class'][] = 'width';
  $form['profile_demand_create']['field_pic_indents_top']['#attributes']['class'][] = 'width';
  $form['profile_demand_create']['field_pic_indents_text']['#attributes']['class'][] = 'width';
  $form['profile_demand_create']['field_pic_indents_pic']['#attributes']['class'][] = 'width';
  $form['profile_demand_create']['field_formula_indents_formula']['#attributes']['class'][] = 'width';
  $form['profile_demand_create']['field_main_width_number2']['#attributes']['class'][] = 'width';
  $form['profile_demand_create']['field_main_width_width']['#attributes']['class'][] = 'width';
  $form['profile_demand_create']['field_main_width_width2']['#attributes']['class'][] = 'width';
  $form['profile_demand_create']['field_main_width_space']['#attributes']['class'][] = 'width';
  $form['profile_demand_create']['field_main_width_space2']['#attributes']['class'][] = 'width';
  $form['profile_demand_create']['field_main_margins_str']['#attributes']['class'][] = 'width_sel';
  $form['profile_demand_create']['field_main_interval_str']['#attributes']['class'][] = 'width_sel';
  $form['profile_demand_create']['field_demand_name']['#attributes']['class'][] = 'inline_label';
  $form['profile_demand_create']['field_demand_note']['#attributes']['class'][] = 'inline_label';
  $form['profile_demand_create']['field_header_filter_skip']['#attributes']['class'][] = 'inline_label';
  $form['profile_demand_create']['field_number_main_division']['#attributes']['class'][] = 'inline_label';
  $form['profile_demand_create']['field_title_number_division']['#attributes']['class'][] = 'inline_label';
  $form['profile_demand_create']['field_pic_size_2']['#attributes']['class'][] = 'inline_label';
  $form['profile_demand_create']['field_pic_border_color']['#attributes']['class'][] = 'inline_label';
  $form['profile_demand_create']['field_pic_number_division']['#attributes']['class'][] = 'inline_label';
  $form['profile_demand_create']['field_pic_indents_text']['#attributes']['class'][] = 'inline_label';
  $form['profile_demand_create']['field_pic_indents_pic']['#attributes']['class'][] = 'inline_label';
  $form['profile_demand_create']['field_table_number_division']['#attributes']['class'][] = 'inline_label';
  $form['profile_demand_create']['field_formula_indents_formula']['#attributes']['class'][] = 'inline_label';
  $form['profile_demand_create']['field_formula_number_division']['#attributes']['class'][] = 'inline_label';
  $form['profile_demand_create']['field_list_formatting_indentatio']['#attributes']['class'][] = 'inline_label';
  $form['profile_demand_create']['field_list_formatting_number']['#attributes']['class'][] = 'inline_label';
  $form['profile_demand_create']['field_list_number_division']['#attributes']['class'][] = 'inline_label';
  $form['profile_demand_create']['field_contents_main_division']['#attributes']['class'][] = 'inline_label';
  $form['profile_demand_create']['field_main_columns_text']['und']['#options'][0] = '<span></span>' . 'Одна';
  $form['profile_demand_create']['field_main_columns_text']['und']['#options'][1] = '<span></span>' . 'Две';
  $form['profile_demand_create']['field_main_columns_text']['und']['#options'][2] = '<span></span>' . 'Три';
  $form['profile_demand_create']['field_main_columns_text']['und']['#options'][3] = '<span></span>' . 'Слева';
  $form['profile_demand_create']['field_main_columns_text']['und']['#options'][4] = '<span></span>' . 'Справа';
  $form['profile_demand_create']['field_main_columns_text']['#attributes']['class'][4] = 'n_visibl_r';

  $form['profile_demand_create']['confirm_button1'] = array(
    '#type'   => 'submit',
    '#value'  => 'СОХРАНИТЬ ШАБЛОН',
    '#weight'  => 3,
  );

  $form['profile_demand_create']['confirm_button2'] = array(
    '#type'   => 'submit',
    '#value'  => 'СОХРАНИТЬ ШАБЛОН',
    '#weight'  => 250,
  );

}
