<?php

/**
 * Implements hook_form_FORM_ID_alter().
 */
function gost_profile_form_user_register_form_alter(&$form, &$form_state, $form_id) {
  $form['account']['name']['#description'] = '';
  $form['account']['name']['#attributes']['placeholder'] = t('Имя');
  $form['account']['mail']['#description'] = '';
  $form['account']['mail']['#attributes']['placeholder'] = t('Электронная почта');
  $form['field_mobilenumber']['und']['0']['value']['#attributes']['placeholder'] = t('Мобильный телефон');
  $form['account']['pass']['#description'] = '';
  $form['account']['pass']['#process'] = array('form_process_password_confirm', 'register_alter_password_confirm');
}

function register_alter_password_confirm($element) {
  $element['pass1']['#attributes']['placeholder'] = t("Пароль");
  $element['pass2']['#attributes']['placeholder'] = t("Повторите пароль");
  return $element;
}

function gost_profile_form_user_pass_alter(&$form, &$form_state, $form_id) {
  $form['name']['#title'] = t('Если вы забыли пароль для входа на сайт, введите адрес электронной почты, который вы указывали при регистрации');
  $form['name']['#attributes']['placeholder'] = t('Электронная почта');
}

function gost_profile_form_profile2_form_alter(&$form, &$form_state) {
  if($form['#user_category'] == 'company_info'){
    drupal_set_title('Информация о компании');
  }
}
