<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.6.1 setup script
 * Date: Sun, 22 May 2016 11:04:05 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: Drupal [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'Drupal';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = 8080;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'k1b8c3a4';

/* End of servers configuration */

$cfg['blowfish_secret'] = '574191643e6eb3.54901860';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>